import baseRouter from './worker-router.js';
import { buildMathBank } from './math-bank-runtime-v3.js';
import { buildEnglishBank } from './english-bank-runtime.js';
const REVIEWER_MODEL='gemini-3.5-flash';
const REVIEWER_URL=`https://generativelanguage.googleapis.com/v1beta/models/${REVIEWER_MODEL}:generateContent`;
const reviewSchema={type:'OBJECT',properties:{reviews:{type:'ARRAY',items:{type:'OBJECT',properties:{id:{type:'STRING'},verdict:{type:'STRING',enum:['approved','needs_review','rejected']},score:{type:'INTEGER',minimum:0,maximum:100},reasons:{type:'ARRAY',items:{type:'STRING'}},flags:{type:'ARRAY',items:{type:'STRING',enum:['math_error','skill_drift','ambiguous','weak_explanation','repetitive','language_issue','none']}}},required:['id','verdict','score','reasons','flags']}}},required:['reviews']};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function loadCurriculum(request,env){const r=await env.ASSETS.fetch(new Request(new URL('/data/core-curriculum-v2.json',request.url)));if(!r.ok)throw new Error('core-curriculum-v2.json tidak tersedia');return r.json()}
const normalize=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' ');
function deterministicIntegrity(q){const f=[];if(q.type!=='choice'||!Array.isArray(q.o)||q.o.length!==4)f.push('format_invalid');if(!Number.isInteger(q.a)||q.a<0||q.a>3)f.push('answer_index_invalid');if(Array.isArray(q.o)&&new Set(q.o.map(normalize)).size!==4)f.push('duplicate_options');if(!String(q.q||'').trim())f.push('empty_stem');if(!String(q.why||'').trim())f.push('empty_explanation');return f}
async function callReviewer(questions,meta,env){if(!env.GEMINI_API_KEY)throw new Error('GEMINI_API_KEY belum dikonfigurasi.');const rubric=meta.subject==='Matematika'?'Periksa kebenaran matematika, tepat satu jawaban benar, ambiguity, skill alignment, literasi/numerasi, kualitas explanation, dan repetisi.':'Periksa grammar/vocabulary, tepat satu jawaban benar, ambiguity, skill alignment, bahasa sesuai usia, reading literacy, explanation, dan repetisi. English target harus tetap dominan; bantuan Indonesia hanya bila perlu.';const age=meta.grade===1?'Kelas 1: frasa/kalimat sangat pendek, konkret, recognition sederhana.':meta.grade===2?'Kelas 2: simple sentences dan konteks ringan dengan 1-2 informasi.':'Kelas 3: short contextual reading dan sentence patterns yang tetap familiar.';const prompt=`Anda reviewer editorial soal ${meta.subject} SD/MI/SDIT Indonesia. Nilai soal yang dipakai aplikasi PahamBelajar. ${age} ${rubric} Helper text bukan bagian stem. Approved hanya jika aman ditampilkan ke anak.\nKelas ${meta.grade}, Semester ${meta.semester}, Bab ${meta.chapterTitle}.\nSOAL:\n${JSON.stringify(questions)}`;const r=await fetch(REVIEWER_URL,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':env.GEMINI_API_KEY},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',responseSchema:reviewSchema,temperature:0.1}})});if(!r.ok)throw new Error(`Reviewer Gemini gagal (${r.status}).`);const p=await r.json(),text=p?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'';return JSON.parse(text).reviews||[]}
function bankFor(curriculum,grade,subject){return subject==='Bahasa Inggris'?buildEnglishBank(curriculum,grade):buildMathBank(curriculum,grade)}
async function runtimeReview(request,env){try{const u=new URL(request.url),grade=Number(u.searchParams.get('grade')),semester=Number(u.searchParams.get('semester')),chapterId=String(u.searchParams.get('chapter_id')||''),subject=u.searchParams.get('subject')==='Bahasa Inggris'?'Bahasa Inggris':'Matematika';if(![1,2,3].includes(grade)||![1,2].includes(semester)||!chapterId)return json({error:'grade, semester, dan chapter_id wajib valid.'},400);const c=await loadCurriculum(request,env),chapter=(c?.grades?.[String(grade)]?.semesters?.[String(semester)]?.[subject]||[]).find(x=>x.id===chapterId);if(!chapter)return json({error:'Bab tidak ditemukan.'},404);const bank=bankFor(c,grade,subject),runtime=bank?.chapters?.[chapter.title];if(!runtime)return json({error:'Runtime bank bab tidak ditemukan.'},404);const questions=runtime.practice||[],integrity=questions.map(q=>({id:q.id,flags:deterministicIntegrity(q)})).filter(x=>x.flags.length),reviews=await callReviewer(questions,{grade,semester,chapterTitle:chapter.title,subject},env),byId=new Map(reviews.map(r=>[r.id,r]));const results=questions.map(q=>{const det=integrity.find(x=>x.id===q.id),review=byId.get(q.id)||{verdict:'needs_review',score:0,reasons:['Reviewer tidak mengembalikan hasil.'],flags:['language_issue']};return{...q,review_status:det?'rejected-deterministic':review.verdict==='approved'&&review.score>=85?'approved-auto':review.verdict==='rejected'?'rejected-ai':'needs-review',review:{...review,deterministic_flags:det?.flags||[]}}});const summary={total:results.length,approved:results.filter(x=>x.review_status==='approved-auto').length,needs_review:results.filter(x=>x.review_status==='needs-review').length,rejected:results.filter(x=>x.review_status.startsWith('rejected')).length};return json({ok:true,publish:false,models:{reviewer:REVIEWER_MODEL},scope:{subject,grade,semester,chapter:{id:chapter.id,title:chapter.title}},bank_version:bank.version,summary,production_ready:summary.total>0&&summary.approved===summary.total,results})}catch(e){return json({error:e.message||'Runtime bank review gagal.'},502)}}
export default{async fetch(request,env){const u=new URL(request.url);const m=u.pathname.match(/^\/data\/question-bank-english-g([1-3])-v1\.json$/);if(m){try{const c=await loadCurriculum(request,env),bank=buildEnglishBank(c,Number(m[1]));return bank?json(bank):json({error:'Kelas tidak ditemukan.'},404)}catch(e){return json({error:e.message},500)}}if(u.pathname==='/api/ai/runtime-bank-review'&&request.method==='GET')return runtimeReview(request,env);return baseRouter.fetch(request,env)}};